CREATE TABLE user_profile
(
    user_profile_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name        VARCHAR(45),
    last_name         VARCHAR(45),
    email             VARCHAR(45)                             NOT NULL,
    contact_number    VARCHAR(12)                             NOT NULL,
    address           VARCHAR(255),
    gender            VARCHAR(255),
    birth_date        TIMESTAMP WITHOUT TIME ZONE,
    profile_image_url VARCHAR(255),
    CONSTRAINT pk_userprofile PRIMARY KEY (user_profile_id)
);

ALTER TABLE clients
    ADD notes VARCHAR(255);

ALTER TABLE clients
    ADD status SMALLINT;

ALTER TABLE clients
    ADD user_profile_id BIGINT;

ALTER TABLE veterinarians
    ADD user_profile_id BIGINT;

ALTER TABLE clients
    ADD CONSTRAINT FK_CLIENTS_ON_USER_PROFILE FOREIGN KEY (user_profile_id) REFERENCES user_profile (user_profile_id);

ALTER TABLE veterinarians
    ADD CONSTRAINT FK_VETERINARIANS_ON_USER_PROFILE FOREIGN KEY (user_profile_id) REFERENCES user_profile (user_profile_id);

ALTER TABLE clients
DROP
COLUMN address;

ALTER TABLE clients
DROP
COLUMN age;

ALTER TABLE clients
DROP
COLUMN contact_number;

ALTER TABLE clients
DROP
COLUMN email;

ALTER TABLE clients
DROP
COLUMN first_name;

ALTER TABLE clients
DROP
COLUMN gender;

ALTER TABLE clients
DROP
COLUMN last_name;

ALTER TABLE veterinarians
DROP
COLUMN address;

ALTER TABLE veterinarians
DROP
COLUMN age;

ALTER TABLE veterinarians
DROP
COLUMN contact_number;

ALTER TABLE veterinarians
DROP
COLUMN email;

ALTER TABLE veterinarians
DROP
COLUMN first_name;

ALTER TABLE veterinarians
DROP
COLUMN last_name;

ALTER TABLE users
DROP
COLUMN contact_number;

ALTER TABLE users
DROP
COLUMN first_name;

ALTER TABLE users
DROP
COLUMN last_name;

ALTER TABLE users
DROP
COLUMN profile_image_url;